# Generated by Django 4.1.1 on 2022-09-24 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_place_category_alter_reels_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='en_video',
            field=models.FileField(upload_to='video', validators=[django.core.validators.FileExtensionValidator(['MPG', 'MP2', 'MPEG', 'MPE', 'MPV', 'MP4', 'M4P', 'M4V', 'AVCHD'])]),
        ),
    ]
