# Generated by Django 4.1.1 on 2022-09-24 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reels_en_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='en_video',
            field=models.FileField(upload_to='video', validators=[django.core.validators.FileExtensionValidator(['mpg', 'mp2', 'mpeg', 'mpe', 'mpv', 'mp4', 'm4p', 'm4v', 'avchd'])]),
        ),
    ]
